"""thread per contact, reply mark on contact

Revision ID: 2f2479cffc0e
Revises: 3b5fac68d5f9
Create Date: 2026-09-19 01:04:13.249957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f2479cffc0e'
down_revision: Union[str, Sequence[str], None] = '3b5fac68d5f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('last_replied_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('threads', sa.Column('contact_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_threads_domain_campaign'), 'threads', type_='unique')
    op.create_index('idx_threads_domain', 'threads', ['domain_id'], unique=False)
    op.create_unique_constraint('uq_threads_domain_campaign_contact', 'threads', ['domain_id', 'campaign_id', 'contact_id'])
    # Имя задано явно: безымянное ограничение нечем удалить при откате.
    op.create_foreign_key(
        'fk_threads_contact_id', 'threads', 'contacts', ['contact_id'], ['id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_threads_contact_id', 'threads', type_='foreignkey')
    op.drop_constraint('uq_threads_domain_campaign_contact', 'threads', type_='unique')
    op.drop_index('idx_threads_domain', table_name='threads')
    op.create_unique_constraint(op.f('uq_threads_domain_campaign'), 'threads', ['domain_id', 'campaign_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('threads', 'contact_id')
    op.drop_column('contacts', 'last_replied_at')
    # ### end Alembic commands ###
