"""initial schema: 12 core tables

Revision ID: 4763b9a0e07d
Revises: 
Create Date: 2026-09-18 16:32:32.373365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4763b9a0e07d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=253), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host')
    )
    op.create_index('idx_domains_host', 'domains', ['host'], unique=False)
    op.create_table('run_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('min_dr', sa.Integer(), nullable=False),
    sa.Column('min_org_traffic', sa.Integer(), nullable=False),
    sa.Column('min_refdomains', sa.Integer(), nullable=False),
    sa.Column('min_keywords', sa.Integer(), nullable=False),
    sa.Column('geo_top_n', sa.Integer(), nullable=False),
    sa.Column('geo_min_share', sa.Float(), nullable=False),
    sa.Column('metrics_ttl_days', sa.Integer(), nullable=False),
    sa.Column('price_ttl_days', sa.Integer(), nullable=False),
    sa.Column('units_cap', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_run_settings_version', 'run_settings', ['version'], unique=False)
    op.create_table('senders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=253), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('stage', sa.Enum('donors', 'advertisers', name='stage'), nullable=False),
    sa.Column('daily_cap', sa.Integer(), nullable=False),
    sa.Column('sent_today', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('free', 'working', 'paused', name='senderstatus'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('warmup_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pause_reason', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_senders_domain', 'senders', ['domain'], unique=False)
    op.create_index('idx_senders_stage_status', 'senders', ['stage', 'status'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('source', sa.Enum('page', 'whois', 'provider', 'manual', name='contactsource'), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=True),
    sa.Column('verification_score', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id', 'email', name='uq_contacts_domain_email')
    )
    op.create_index('idx_contacts_domain_id', 'contacts', ['domain_id'], unique=False)
    op.create_table('donors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('suitable', 'unsuitable', 'unchecked', name='donorstatus'), nullable=False),
    sa.Column('reject_reason', sa.String(length=64), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dr', sa.Integer(), nullable=True),
    sa.Column('org_traffic', sa.Integer(), nullable=True),
    sa.Column('geo', sa.String(length=8), nullable=True),
    sa.Column('geo_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('geo_top_share', sa.Float(), nullable=True),
    sa.Column('geo_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_price_usd', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('last_price_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contact_status', sa.Enum('found', 'not_found', 'form_only', 'no_quota', 'rate_limited', 'error', name='contactstatus'), nullable=True),
    sa.Column('contact_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id')
    )
    op.create_index('idx_donors_dr', 'donors', ['dr'], unique=False)
    op.create_index('idx_donors_geo', 'donors', ['geo'], unique=False)
    op.create_index('idx_donors_metrics_refreshed', 'donors', ['metrics_refreshed_at'], unique=False)
    op.create_index('idx_donors_status', 'donors', ['status'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('donors', 'advertisers', name='stage'), nullable=False),
    sa.Column('settings_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('estimating', 'running', 'done', 'stopped', name='runstatus'), nullable=False),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('estimated_units', sa.Integer(), nullable=True),
    sa.Column('actual_units', sa.Integer(), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['settings_id'], ['run_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_runs_status', 'runs', ['status'], unique=False)
    op.create_table('suppressions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Enum('unsubscribed', 'complained', 'supplier', 'manual', name='suppressionreason'), nullable=False),
    sa.Column('stage', sa.Enum('donors', 'advertisers', name='stage'), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_suppressions_domain_id', 'suppressions', ['domain_id'], unique=False)
    op.create_index('idx_suppressions_email', 'suppressions', ['email'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.Enum('donors', 'advertisers', name='stage'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('template_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.Enum('ahrefs', 'serp', 'llm', 'email', name='usageprovider'), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('units', sa.Integer(), nullable=True),
    sa.Column('amount_usd', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usage_provider_created', 'usage_records', ['provider', 'created_at'], unique=False)
    op.create_index('idx_usage_run_id', 'usage_records', ['run_id'], unique=False)
    op.create_table('threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('open', 'replied', 'unsubscribed', 'closed', name='threadstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id', 'campaign_id', name='uq_threads_domain_campaign')
    )
    op.create_index('idx_threads_status', 'threads', ['status'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'sending', 'sent', 'delivered', 'bounced', 'stopped', name='messagestatus'), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('uniqueness_pct', sa.Float(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('idempotency_key', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['senders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_messages_idempotency')
    )
    op.create_index('idx_messages_status_next_action', 'messages', ['status', 'next_action_at'], unique=False)
    op.create_index('idx_messages_thread_id', 'messages', ['thread_id'], unique=False)
    op.create_table('replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('human', 'auto_reply', 'bounce', 'unsubscribe', name='replykind'), nullable=False),
    sa.Column('raw_body', sa.Text(), nullable=False),
    sa.Column('price_white', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('price_grey', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('payment_methods', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=128), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_replies_kind', 'replies', ['kind'], unique=False)
    op.create_index('idx_replies_thread_id', 'replies', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_replies_thread_id', table_name='replies')
    op.drop_index('idx_replies_kind', table_name='replies')
    op.drop_table('replies')
    op.drop_index('idx_messages_thread_id', table_name='messages')
    op.drop_index('idx_messages_status_next_action', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_threads_status', table_name='threads')
    op.drop_table('threads')
    op.drop_index('idx_usage_run_id', table_name='usage_records')
    op.drop_index('idx_usage_provider_created', table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_table('campaigns')
    op.drop_index('idx_suppressions_email', table_name='suppressions')
    op.drop_index('idx_suppressions_domain_id', table_name='suppressions')
    op.drop_table('suppressions')
    op.drop_index('idx_runs_status', table_name='runs')
    op.drop_table('runs')
    op.drop_index('idx_donors_status', table_name='donors')
    op.drop_index('idx_donors_metrics_refreshed', table_name='donors')
    op.drop_index('idx_donors_geo', table_name='donors')
    op.drop_index('idx_donors_dr', table_name='donors')
    op.drop_table('donors')
    op.drop_index('idx_contacts_domain_id', table_name='contacts')
    op.drop_table('contacts')
    op.drop_index('idx_senders_stage_status', table_name='senders')
    op.drop_index('idx_senders_domain', table_name='senders')
    op.drop_table('senders')
    op.drop_index('idx_run_settings_version', table_name='run_settings')
    op.drop_table('run_settings')
    op.drop_index('idx_domains_host', table_name='domains')
    op.drop_table('domains')
    # ### end Alembic commands ###
